services:
  - type: web
    name: alpen_consulting_1
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir src app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
       

