services:
  - type: web
    name: apen_consultion_hiqu
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir src app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
       

